/* Write an Apex code that store 3 numbers in Integer variables
   - Print out the smallest number */

//Task Set 2
//task 2

Integer num1 = 100 , num2 = 200 , num3 = 300 ;

if (num1 <  num2 && num1 < num3) {
    System.debug('The first number is the smallest');
}else if(num2<num1 && num2<num3){
System.debug('The second number is the smallest');
}else if(num2<num1 && num2<num3){
    System.debug('The third number is the smallest');
    }



