/**
TaskSet3
Task4

Create two Integer as startingNumber and endingNumber
initialize their value (startingNumber should be less than endingNumber in this case).
use for loop to count up by one starting from startingNumber and end at endingNumber

 */

//Task Set 3
//task 4
Integer startingNumber = 4 ;
Integer endingNumber = 10 ;

for(Integer count = startingNumber ; count<=endingNumber ; count++){
System.debug(count);

}