/**
Declare and initialize a String variable with one character
check the if character is vowel 'a' , 'e', 'o' , 'u' , 'i'
if true print it's a vowel 
else print it's not a vowel!
 */

//Task Set 1
//task 3
 String variable= 'l' ;
 if(variable=='a' || variable == 'e' || variable == 'o' || variable == 'u' || variable == 'i'){
    System.debug('It is a vowel');
}else{
    System.debug('It is not a vowel');

}
