
/* Declare and initialize an Integer variable. 
checks if a given integer is positive, negative, or zero. 
If the number is positive, the program should print "Positive." 
If the number is negative, the program should print “negative”
Else print Zero
*/

//Task Set 1
//task 2
Integer num = 50;

if(num > 0){
    System.debug('The number is positive');
}else if(num < 0){ 
    System.debug('The number is negative');
}else{
    System.debug('The number is zero');
}


